### ISSUE TITLE
Turn on GitHub Pages

### ISSUE THREAD

**Issue by NickCH-K** [SafeGraphInc/SafeGraphR#2]
Hi there @felixsafegraph ! Not sure whether it's better to reach out here or on Slack. But the SafeGraphR package is ready for beta, and there's a docsite in here now. Could you turn on GitHub pages for the SafeGraphR github (set to docs/)? I don't have access. Thank you!

**Comment by felixsafegraph** [comment]
done! https://safegraphinc.github.io/SafeGraphR
would be great if you share that with the consortium
